### ISSUE TITLE
Grab useful content from other branches

### ISSUE THREAD

**Issue by ryan-policheri** [justinhovey/johndoeforsenate#1]
Look at the other branches and grab useful content to put in the master

**Comment by ryan-policheri** [comment]
Jake = looking through Paul's CSS
Johnathon = looking through Jessica's CSS
Ryan = looking through bootstraps

**Comment by jakepetry** [comment]
I can't find anything from my CSS that we can use.

**Comment by faciojonathan** [comment]
there isn't anything in my CSS to add either

**Comment by ryan-policheri** [comment]
Ok I will make new issues while I continue to put in the bootstrap

**Comment by faciojonathan** [comment]
[cid:624da642-cabb-4b7e-90ea-8ce8221c0785]
